# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

workflow:
   # only run on merge requests and pushes to develop
   rules:
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
        when: never
      - if: '$CI_COMMIT_BRANCH == "develop"'
      - when: never


# run linter
eslint:
   # allow this job to be interrupted by a newer job
   interruptible: true
   script:
      - npm install eslint
      - node_modules/eslint/bin/eslint.js .
